# Default values for celciusfarenheit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: celciusfarenheit
  pullPolicy: Never
  tag: "v1"

logger:
  service:
    port: 9000
    spectate_port: 9001

deployment:
  containerPort: 9090
  sink: "logger:9000"

podAnnotations: {}

service:
  type: ClusterIP
  port: 8000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
