# permissions for end users to view pipelinemodules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipelinemodule-viewer-role
rules:
- apiGroups:
  - ecida.researchable.nl
  resources:
  - pipelinemodules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ecida.researchable.nl
  resources:
  - pipelinemodules/status
  verbs:
  - get
