
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ecida.researchable.nl
  resources:
  - pipelinemodules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecida.researchable.nl
  resources:
  - pipelinemodules/finalizers
  verbs:
  - update
- apiGroups:
  - ecida.researchable.nl
  resources:
  - pipelinemodules/status
  verbs:
  - get
  - patch
  - update
